### ISSUE TITLE
Cannot Save Markers

### ISSUE THREAD

**Issue by eljdavis** [StreptanthusDimensions/Plant_Counter#4]
I am trying to Save Markers and when I try the file for the markers is empty. I am running Fiji, ImageJ 2.0.0-rc-69/1.52n with Java 1.8.0_172 [64-bit]. I keep getting the following error messages as well but I am not sure what they mean. Any assistance would be greatly appreciated.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at PlantCounter.initializeImage(PlantCounter.java:542)
	at PlantCounter.actionPerformed(PlantCounter.java:645)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jnmaloof** [comment]
@eljdavis does this error message happen when you press save makers, or when you initialize image?

**Comment by eljdavis** [comment]
@jnmaloof The error message happens with I press save markers. The image initializes without issue.

**Comment by meganbontrager** [comment]
I get the same error when trying to save the markers. They look okay when I click the "results" button or the "measure" button. And when I open the new file that's created, it's empty.

**Comment by jnmaloof** [comment]
@eljdavis @meganbontrager ,it looks to me like the error trace that @eljdavis posted is from reading markers, not writing.  I could be wrong (and this could maybe help me trace the problem) but you can confirm that the the first three lines of the error when you press the save markers button matches this exactly?

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at PlantCounter.initializeImage(PlantCounter.java:542)
at PlantCounter.actionPerformed(PlantCounter.java:645)
```

**Comment by jnmaloof** [comment]
@eljdavis @meganbontrager I ask because line 645 referenced above is the line that should be called when markers are loaded, not saved

**Comment by meganbontrager** [comment]
The error message I get is slightly different than the one Elizabeth posted:
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: PlantCntrMarkerVector cannot be cast to CellCntrMarkerVector
	at WriteXML.writeXML(WriteXML.java:84)
	at PlantCounter.exportMarkers(PlantCounter.java:819)
	at PlantCounter.actionPerformed(PlantCounter.java:642)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jnmaloof** [comment]
@meganbontrager can you make sure that you ONLY have the latest version of the plant_counter in your plugins folder? (You WANT Plant_Counter-0.1.1.jar, NOT Plant_Counter-0.1.jar) 

Thanks.

**Comment by jnmaloof** [comment]
@meganbontrager @eljdavis I think I figured it out.  The README was linking to the old version.  Please download the new version (README fixed): it should be Plant_Counter-0.1.1.jar .  Please throw out the old version in your plugin folder, place the new in the plugins folder, and restart Fiji.  Sorry for this, but hopefully that is it!

**Comment by meganbontrager** [comment]
I think I have the more recent version - I downloaded it this morning from the "target" directory rather than the README link, moved it to Fiji.app/plugins, and restarted. So I have Plant_Counter-0.1.1.jar only.

**Comment by jnmaloof** [comment]
@meganbontrager,  well darn.  OK back to the think tank.  @eljdavis, if you haven't upgraded to v0.1.1 please do so and let me know if you get the same error as you have been getting, or as Megan gets (or nothing!).

To test whether the downloadable version itself was bad, I threw out the jar I had, downloaded the one from github and installed.  It still works for me, so the problem (unfortunately) is not just that I uploaded a bad version.

**Comment by jnmaloof** [comment]
hah "throughout" > "threw out".  The brain is a funny thing...

**Comment by jnmaloof** [comment]
@eljdavis @meganbontrager @johnny3420 Can you please try new version 0.1.1a?  Please remove v0.1.1 from plugins folder first.

Taking a guess, hard to troubleshoot since I don't have the problem on my computer.

**Comment by jnmaloof** [comment]
@eljdavis @meganbontrager v 0.1.1a works for @johnny3420 , so hopefully will for you too! let me know.

**Comment by eljdavis** [comment]
@jnmaloof @meganbontrager  v 0.1.1a works for me as well, thanks!

**Comment by meganbontrager** [comment]
Me too!

**Comment by jnmaloof** [comment]
Whew!

Julin Maloof
Professor
Department of Plant Biology
1 Shields Ave
University of California, Davis
Davis, CA 95616
(530) 752 8077
